[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1"
crossterm = "0.25"
itertools = "0.10.5"
once_cell = "1.16.0"
rand = "0.8"
regex = "1.7.0"
tui = "0.19"
